import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

(async () => {
	const result = await esbuild.build({
		plugins: [
			// esbuildSvelte({
			// 	compilerOptions: { css: true },
			// 	preprocess: sveltePreprocess(),
			// })
		],
		banner: {
			js: banner,
		},
		entryPoints: ['./src/main.ts'],
		bundle: true,
		external: [
			'obsidian',
			// 'pinyin', // [!code hl] 这个依赖极大，pinyin版保留，而min版去除这个
			...builtins
		],
		format: 'cjs',
		// watch: !prod, // 不再支持
		target: 'es2020',
		logLevel: "info",
		sourcemap: prod ? false : 'inline',
		treeShaking: true,
		outfile: '../../dist-pinyin/main.js',
		// minify: false, // 9.4MB -> 8.1MB
		metafile: true, // 依赖大小分析
	}).catch(() => process.exit(1));

	// 将 metafile 写入磁盘，生成结果可使用 https://esbuild.github.io/analyze/ 进行分析查看
	fs.writeFileSync("esbuild-meta.json", JSON.stringify(result.metafile, null, 2));

	console.log("Build finished. Metafile written to esbuild-meta.json");
})();
