[[categories]]
label = "表格"
key = "table 表格"
type = "md"
content = '''
|     |     |
| --- | --- |
|     |     |

'''

[[categories]]
label = "代码块"
key = "codeblock 代码块"
type = "md"
content = '''
```

```

'''

[[categories]]
label = "数学块"
key = "mathblock 数学块"
type = "md"
content = '''
$$

$$

'''

[[categories]]
label = "脚注"
key = "footnote 脚注"
type = "md"
content = '''
[^1]

[^1]: 

'''
